# coding: utf-8

"""
    PhagesDB API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import phagesdb_client
from phagesdb_client.api.schema_api import SchemaApi  # noqa: E501
from phagesdb_client.rest import ApiException


class TestSchemaApi(unittest.TestCase):
    """SchemaApi unit test stubs"""

    def setUp(self):
        self.api = phagesdb_client.api.schema_api.SchemaApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_schema_list(self):
        """Test case for schema_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
