# coding: utf-8

"""
    PhagesDB API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import phagesdb_client
from phagesdb_client.api.phages_api import PhagesApi  # noqa: E501
from phagesdb_client.rest import ApiException


class TestPhagesApi(unittest.TestCase):
    """PhagesApi unit test stubs"""

    def setUp(self):
        self.api = phagesdb_client.api.phages_api.PhagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_phages_list(self):
        """Test case for phages_list

        Detailed Phage Information  # noqa: E501
        """
        pass

    def test_phages_read(self):
        """Test case for phages_read

        Detailed Phage Information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
