# coding: utf-8

"""
    PhagesDB API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.host_strains_api import HostStrainsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestHostStrainsApi(unittest.TestCase):
    """HostStrainsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.host_strains_api.HostStrainsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_host_strains_list(self):
        """Test case for host_strains_list

        Host Strain Information  # noqa: E501
        """
        pass

    def test_host_strains_phagelist_list(self):
        """Test case for host_strains_phagelist_list

        Phages by Strain  # noqa: E501
        """
        pass

    def test_host_strains_read(self):
        """Test case for host_strains_read

        Host Strain Information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
