# coding: utf-8

"""
    PhagesDB API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.publications_api import PublicationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPublicationsApi(unittest.TestCase):
    """PublicationsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.publications_api.PublicationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_publications_list(self):
        """Test case for publications_list

        """
        pass

    def test_publications_read(self):
        """Test case for publications_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
