# coding: utf-8

"""
    PhagesDB API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.genes_api import GenesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGenesApi(unittest.TestCase):
    """GenesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.genes_api.GenesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_genes_list(self):
        """Test case for genes_list

        Phamerator Gene Information  # noqa: E501
        """
        pass

    def test_genes_read(self):
        """Test case for genes_read

        Phamerator Gene Information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
