# coding: utf-8

"""
    PhagesDB API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.pham_phages_api import PhamPhagesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPhamPhagesApi(unittest.TestCase):
    """PhamPhagesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.pham_phages_api.PhamPhagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_pham_phages_list(self):
        """Test case for pham_phages_list

        Phamerator Phage Information  # noqa: E501
        """
        pass

    def test_pham_phages_read(self):
        """Test case for pham_phages_read

        Phamerator Phage Information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
