# coding: utf-8

"""
    PhagesDB API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sequenced_phages_api import SequencedPhagesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSequencedPhagesApi(unittest.TestCase):
    """SequencedPhagesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.sequenced_phages_api.SequencedPhagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sequenced_phages_list(self):
        """Test case for sequenced_phages_list

        Sequenced Phages Only  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
