# coding: utf-8

"""
    PhagesDB API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.host_species_api import HostSpeciesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestHostSpeciesApi(unittest.TestCase):
    """HostSpeciesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.host_species_api.HostSpeciesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_host_species_list(self):
        """Test case for host_species_list

        Host Species Information  # noqa: E501
        """
        pass

    def test_host_species_phagelist_list(self):
        """Test case for host_species_phagelist_list

        Phages by Species  # noqa: E501
        """
        pass

    def test_host_species_read(self):
        """Test case for host_species_read

        Host Species Information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
