# coding: utf-8

"""
    PhagesDB API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.temperate_phages_api import TemperatePhagesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTemperatePhagesApi(unittest.TestCase):
    """TemperatePhagesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.temperate_phages_api.TemperatePhagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_temperate_phages_list(self):
        """Test case for temperate_phages_list

        Sequenced Temperate Phages  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
