# coding: utf-8

"""
    PhagesDB API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import phagesdb_client
from phagesdb_client.api.clusters_api import ClustersApi  # noqa: E501
from phagesdb_client.rest import ApiException


class TestClustersApi(unittest.TestCase):
    """ClustersApi unit test stubs"""

    def setUp(self):
        self.api = phagesdb_client.api.clusters_api.ClustersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_clusters_list(self):
        """Test case for clusters_list

        Cluster Information  # noqa: E501
        """
        pass

    def test_clusters_phagelist_list(self):
        """Test case for clusters_phagelist_list

        Phages by Cluster  # noqa: E501
        """
        pass

    def test_clusters_read(self):
        """Test case for clusters_read

        Cluster Information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
